# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel_num', models.CharField(max_length=11)),
                ('china_id', models.CharField(max_length=16)),
            ],
        ),
    ]
